# Generated by Django 4.2.7 on 2023-11-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(blank=True, default='', max_length=100)),
                ('Precio', models.CharField(blank=True, default='', max_length=100)),
                ('Cantidad', models.CharField(blank=True, default='', max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(blank=True, default='', max_length=100)),
                ('Telefono', models.CharField(blank=True, default='', max_length=100)),
                ('Cantidad', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_usuario', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Cantidad', models.CharField(blank=True, default='', max_length=100)),
                ('Precio_unitario', models.CharField(blank=True, default='', max_length=100)),
                ('Fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
